name: Docker Compose Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and run Docker-compose
        run: docker-compose up -d
      - name: Run tests
        run: |
          curl http://localhost:3000
      - name: Stop and remove containers
        run: docker-compose down
