name: Docker Compose Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build
      - name: Run Docker-compose
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml ps
          sleep 30
      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml run --rm nodejs sh -c "curl -sSf http://nodejs:3000"
      - name: Stop and remove containers
        run: docker-compose -f docker-compose.yml down
